name: power_bank
description: PowerBank app

publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_tracking_transparency: ^2.0.2+4
  cupertino_icons: ^1.0.2
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.0.1
  #https://pub.dev/packages/rxdart
  rxdart: ^0.27.1
  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^4.2.0
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.5
  #https://pub.dev/packages/dartz
  dartz: ^0.9.2
  #https://pub.dev/packages/data_connection_checker
  data_connection_checker: ^0.3.4
  #https://pub.dev/packages/dio
  dio: ^4.0.0
  #https://pub.dev/packages/retrofit
  retrofit: ^3.0.1+1
  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.0.1
  #https://pub.dev/packages/formz
  formz: ^0.4.0
  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.1+1
  #https://pub.dev/packages/get_it
  get_it: ^7.2.0
  #https://pub.dev/packages/intl
  intl: ^0.17.0
  #https://pub.dev/packages/flutter_keyboard_visibility
  keyboard_visibility: ^0.5.6
  #https://pub.dev/packages/libphonenumber_plugin
  libphonenumber_plugin: ^0.2.3
  #https://pub.dev/packages/flutter_libphonenumber
  flutter_libphonenumber: ^1.2.2
  #https://pub.dev/packages/flutter_country
  flutter_country: ^0.1.1
  #https://pub.dev/packages/devicelocale
  devicelocale: ^0.5.0
  #https://pub.dev/packages/freezed
  freezed: ^1.1.1
  #https://pub.dev/packages/camera
  camera: ^0.9.4+11
  #https://pub.dev/packages/flutter_xlider
  flutter_xlider: ^3.4.0
  #https://pub.dev/packages/pausable_timer
  pausable_timer: ^1.0.0+1
  #https://pub.dev/packages/dotted_decoration
  dotted_decoration: ^2.0.0
#  #https://pub.dev/packages/permission_handler
#  permission_handler: ^9.2.0
  #https://pub.dev/packages/webview_flutter
  webview_flutter: ^3.0.2
  #https://pub.dev/packages/sms_autofill
  sms_autofill: ^2.2.0
  #https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.1.8
  #https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0
  #https://pub.dev/packages/qr_code_scanner
  qr_code_scanner: ^1.0.0
  #https://pub.dev/packages/geolocator
  geolocator: ^9.0.1
  #https://pub.dev/packages/flutter_scale_tap
  flutter_scale_tap: ^1.0.5
  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.20
  #https://pub.dev/packages/web_socket_channel
  web_socket_channel: ^2.1.0
  #https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^11.2.8
  #https://pub.dev/packages/firebase_core
  firebase_core : ^1.13.1
  #https://pub.dev/packages/overlay_support
  overlay_support: ^1.2.1
  #https://pub.dev/packages/mask_text_input_formatter/install
  mask_text_input_formatter: ^2.1.0
  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^1.4.0
  #https://pub.dev/packages/back_button_interceptor
  back_button_interceptor: ^5.0.2
  #https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.4

dev_dependencies:
  retrofit_generator: ^4.0.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  json_serializable: ^6.1.4
  analyzer: ^3.2.0
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  flutter_gen_runner: ^4.1.5


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

flutter_native_splash:
  background_image: assets/images/splash_background.png
